apiVersion: v2
name: apex
description: APEX — Autonomous Predictive & EXecutive Race Intelligence Enterprise Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - f1
  - telemetry
  - machine-learning
  - kafka
  - bullmq
  - digital-twin
home: https://github.com/Susil-commits/F1-s-APEX----Autonomous-Predictive-EXecutive-Race-Intelligence-
maintainers:
  - name: APEX Race Engineering Team
