"""Event schemas for Kafka multi-topic telemetry streaming in APEX."""
import time
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class BaseStreamingEvent(BaseModel):
    """Base model for all streaming events on the APEX message broker."""
    event_id: str = Field(..., description="Unique event UUID")
    session_id: str = Field(..., description="Race simulation session or grand prix ID")
    timestamp: float = Field(default_factory=time.time, description="Unix timestamp (seconds.microseconds)")
    event_type: str = Field(..., description="Discriminator event type")
    source: str = Field(default="APEX-DigitalTwin", description="Originating producer service")
    trace_id: Optional[str] = Field(default=None, description="OpenTelemetry W3C distributed trace ID")


class TelemetryEvent(BaseStreamingEvent):
    """Real-time 60Hz vehicle telemetry payload for a single car."""
    event_type: str = "TELEMETRY_SAMPLE"
    car_id: str
    driver_name: str
    driver_code: str
    team_name: str
    lap_number: int
    lap_progress: float = Field(ge=0.0, le=1.0, description="Normalized track progress 0.0 -> 1.0")
    speed_kmh: float
    throttle_pct: float = Field(ge=0.0, le=100.0)
    brake_pct: float = Field(ge=0.0, le=100.0)
    gear: int = Field(ge=0, le=8)
    rpm: int = Field(ge=0, le=16000)
    drs_active: bool = False
    fuel_remaining_kg: float = Field(ge=0.0)
    tyre_compound: str
    tyre_surface_temp_c: float
    tyre_carcass_temp_c: float
    position: int = Field(ge=1, le=20)
    gap_to_leader_s: float = 0.0
    interval_to_ahead_s: float = 0.0


class WeatherEvent(BaseStreamingEvent):
    """Atmospheric and track condition telemetry event."""
    event_type: str = "WEATHER_UPDATE"
    air_temp_c: float
    track_temp_c: float
    humidity_pct: float
    rain_intensity_pct: float = Field(ge=0.0, le=100.0)
    track_wetness_index: float = Field(ge=0.0, le=1.0)
    forecast_next_10min_rain_prob: float = Field(ge=0.0, le=1.0)
    wind_speed_kmh: float = 0.0
    wind_direction_deg: float = 0.0


class TyreDegradationEvent(BaseStreamingEvent):
    """Physics-informed tyre degradation and thermal stress notification."""
    event_type: str = "TYRE_DEGRADATION"
    car_id: str
    compound: str
    stint_lap_age: int
    wear_percentage: float = Field(ge=0.0, le=100.0)
    thermal_deg_index: float
    pinn_residual_offset: float
    cliff_proximity_pct: float = Field(ge=0.0, le=100.0)
    estimated_laps_remaining: float
    is_cliff_breached: bool = False


class RaceControlEvent(BaseStreamingEvent):
    """Official FIA race control and safety car intervention events."""
    event_type: str = "RACE_CONTROL"
    flag_status: str = Field(description="GREEN | YELLOW | DOUBLE_YELLOW | VSC | SAFETY_CAR | RED")
    sector_affected: Optional[int] = None
    message: str
    incident_car_id: Optional[str] = None
    laps_under_neutralization: int = 0
    drs_disabled: bool = False


class StrategyDecisionEvent(BaseStreamingEvent):
    """Strategic decision payload generated by the Hybrid Decision Engine."""
    event_type: str = "STRATEGY_DECISION"
    target_car_id: str
    lap_number: int
    recommended_action: str
    confidence_score: float = Field(ge=0.0, le=1.0)
    urgency_level: str = "MEDIUM"
    monte_carlo_p_win: float = 0.0
    dqn_q_value: float = 0.0
    primary_reason: str
    candidate_scores: Dict[str, float] = Field(default_factory=dict)


class DeadLetterEvent(BaseModel):
    """Envelope for poisoned, unparseable, or failed events routed to DLQ."""
    dlq_id: str
    original_topic: str
    raw_payload: str
    error_reason: str
    failed_at: float = Field(default_factory=time.time)
    retry_count: int = 0
    source_consumer_group: str
